### ISSUE TITLE
Corrections on the main page

### ISSUE THREAD

**Issue by Serameth** [FueledByOCHD/Realms-Invasion-Info-Center#1]
1) things are subject to change alot between releases
--> things are subject to a lot of changes between releases

2) so please I ask you keep coming back from time to time
--> so make sure to occasionally return for the most recent and up-to-date version release

3) with more of a Sci-Fi Fantasy theme. with a end goal of being transforming into a game of its own.
--> with more of a Sci-Fi Fantasy theme. The end goal is to eventually transform this into a game of its own.

**Comment by FueledByOCHD** [comment]
This one will be closed with next commit
